# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Filter.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Filter(object):
    def setupUi(self, Filter):
        if not Filter.objectName():
            Filter.setObjectName(u"Filter")
        Filter.resize(1119, 766)
        self.returnMainWin = QPushButton(Filter)
        self.returnMainWin.setObjectName(u"returnMainWin")
        self.returnMainWin.setGeometry(QRect(1030, 720, 81, 41))
        font = QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.returnMainWin.setFont(font)
        self.lineEdit_2 = QLineEdit(Filter)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(170, 350, 81, 20))
        self.lineEdit = QLineEdit(Filter)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(170, 310, 81, 20))
        self.lineEdit_3 = QLineEdit(Filter)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(170, 390, 81, 20))
        self.lineEdit_4 = QLineEdit(Filter)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(170, 430, 81, 20))
        self.label = QLabel(Filter)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(50, 310, 71, 20))
        self.label_2 = QLabel(Filter)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(260, 320, 54, 12))
        self.label_3 = QLabel(Filter)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(260, 360, 54, 12))
        self.label_4 = QLabel(Filter)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(260, 400, 54, 12))
        self.pushButton = QPushButton(Filter)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 720, 75, 41))
        font1 = QFont()
        font1.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        font1.setPointSize(13)
        self.pushButton.setFont(font1)
        self.label_5 = QLabel(Filter)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(50, 280, 54, 12))
        font2 = QFont()
        font2.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        self.label_5.setFont(font2)
        self.label_6 = QLabel(Filter)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(250, 280, 54, 12))
        self.label_6.setFont(font2)
        self.label_7 = QLabel(Filter)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(50, 350, 71, 20))
        self.progressBar = QProgressBar(Filter)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(100, 750, 921, 20))
        self.progressBar.setValue(24)
        self.label_8 = QLabel(Filter)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(260, 440, 54, 12))
        self.lineEdit_5 = QLineEdit(Filter)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(170, 130, 81, 20))
        self.label_9 = QLabel(Filter)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(260, 140, 54, 12))
        self.label_10 = QLabel(Filter)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(50, 390, 71, 20))
        self.label_11 = QLabel(Filter)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(50, 430, 71, 20))
        self.label_12 = QLabel(Filter)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(60, 130, 71, 20))
        self.comboBox = QComboBox(Filter)
        self.comboBox.addItem("低通")
        self.comboBox.addItem("高通")
        self.comboBox.addItem("带通")
        self.comboBox.addItem("带阻")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setEnabled(True)
        self.comboBox.setGeometry(QRect(170, 180, 81, 22))
        self.label_13 = QLabel(Filter)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(60, 180, 71, 20))
        self.pushButton_2 = QPushButton(Filter)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(40, 30, 75, 31))

        self.retranslateUi(Filter)

        QMetaObject.connectSlotsByName(Filter)
    # setupUi

    def retranslateUi(self, Filter):
        Filter.setWindowTitle(QCoreApplication.translate("Filter", u"Form", None))
        self.returnMainWin.setText(QCoreApplication.translate("Filter", u"\u8fd4\u56de", None))
        self.label.setText(QCoreApplication.translate("Filter", u"\u901a\u5e26\u622a\u6b62\u9891\u7387", None))
        self.label_2.setText(QCoreApplication.translate("Filter", u"Hz", None))
        self.label_3.setText(QCoreApplication.translate("Filter", u"Hz", None))
        self.label_4.setText(QCoreApplication.translate("Filter", u"dB", None))
        self.pushButton.setText(QCoreApplication.translate("Filter", u"\u5f00\u59cb", None))
        self.label_5.setText(QCoreApplication.translate("Filter", u"\u8f93\u5165\u53c2\u6570", None))
        self.label_6.setText(QCoreApplication.translate("Filter", u"\u5355\u4f4d", None))
        self.label_7.setText(QCoreApplication.translate("Filter", u"\u963b\u5e26\u622a\u6b62\u9891\u7387", None))
        self.label_8.setText(QCoreApplication.translate("Filter", u"dB", None))
        self.label_9.setText(QCoreApplication.translate("Filter", u"Hz", None))
        self.label_10.setText(QCoreApplication.translate("Filter", u"\u963b\u5e26\u622a\u6b62\u9891\u7387", None))
        self.label_11.setText(QCoreApplication.translate("Filter", u"\u963b\u5e26\u622a\u6b62\u9891\u7387", None))
        self.label_12.setText(QCoreApplication.translate("Filter", u"\u91c7\u6837\u7387", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("Filter", u"\u4f4e\u901a", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("Filter", u"\u5e26\u901a", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("Filter", u"\u9ad8\u901a", None))
        self.comboBox.setItemText(3, "")

        self.comboBox.setCurrentText(QCoreApplication.translate("Filter", u"\u4f4e\u901a", None))
        self.label_13.setText(QCoreApplication.translate("Filter", u"\u6ee4\u6ce2\u5668\u79cd\u7c7b", None))
        self.pushButton_2.setText(QCoreApplication.translate("Filter", u"\u9009\u62e9\u6587\u4ef6", None))
    # retranslateUi

